# -*- coding: utf-8 -*-
"""HiMCM25 (jupyter).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y2UK3Z4mY_ki75DfbI5OUQf-eeKRa2wt
"""

df = pd.read_csv("HiMCM 2025 - World Cup Processed Data.csv")
df.columns = df.columns.str.strip()

# Clean 'CO2' column
df["CO2"] = df["CO2"].astype(str).str.replace("net 0", "0", regex=False) # Replace 'net 0' with '0'
df["CO2"] = df["CO2"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["CO2"] = pd.to_numeric(df["CO2"], errors='coerce') # Convert to numeric, coercing errors

# Clean 'Energy' column
df["Energy"] = df["Energy"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["Energy"] = pd.to_numeric(df["Energy"], errors='coerce') # Ensure numeric

# Clean 'Waste' column
df["Waste"] = df["Waste"].astype(str).str.replace("%", "", regex=False) # Remove percentage sign
df["Waste"] = pd.to_numeric(df["Waste"], errors='coerce') # Convert to numeric

# Clean 'Water' column
df["Water"] = pd.to_numeric(df["Water"], errors='coerce') # Ensure numeric

# Fill NaN values with the mean of their respective columns
for col in ["CO2", "Energy", "Waste", "Water"]:
    if df[col].isnull().any(): # Check if there are any NaN values in the column
        mean_value = df[col].mean()
        df[col] = df[col].fillna(mean_value)


required_cols = ["CO2", "Energy", "Waste", "Water"]
assert all(col in df.columns for col in required_cols), \
    f"CSV must contain: {required_cols}"

df.head()

import pandas as pd
import numpy as np

# CSV filename
csv_file = "HiMCM 2025 - Processed Data (2)"  # <-- CHANGE THIS

# weights MUST sum to 1
weights = {
    "CO2 emissions (Tons)": 0.4,
    "Energy": 0.3,
    "Waste": 0.2,
    "Water": 0.1
}

df = pd.read_csv("HiMCM 2025 - Processed Data (2).csv")

# Clean 'CO2' column
df["CO2"] = df["CO2"].astype(str).str.replace("net 0", "0", regex=False) # Replace 'net 0' with '0'
df["CO2"] = df["CO2"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["CO2"] = pd.to_numeric(df["CO2"], errors='coerce') # Convert to numeric, coercing errors

# Clean 'Energy' column
df["Energy"] = df["Energy"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["Energy"] = pd.to_numeric(df["Energy"], errors='coerce') # Ensure numeric

# Clean 'Waste' column
df["Waste"] = df["Waste"].astype(str).str.replace("%", "", regex=False) # Remove percentage sign
df["Waste"] = pd.to_numeric(df["Waste"], errors='coerce') # Convert to numeric

# Clean 'Water' column
df["Water"] = pd.to_numeric(df["Water"], errors='coerce') # Ensure numeric

# Fill NaN values with the mean of their respective columns
for col in ["CO2", "Energy", "Waste", "Water"]:
    if df[col].isnull().any(): # Check if there are any NaN values in the column
        mean_value = df[col].mean()
        df[col] = df[col].fillna(mean_value)


required_cols = ["CO2", "Energy", "Waste", "Water"]
assert all(col in df.columns for col in required_cols), \
    f"CSV must contain: {required_cols}"

df.head()

def normalize(series):
    return np.clip((series - series.min()) / (series.max() - series.min()), 0, 1)

df["n_CO2"] = normalize(df["CO2"])
df["n_Energy"] = normalize(df["Energy"])
df["n_Waste"] = normalize(df["Waste"])
df["n_Water"] = normalize(df["Water"])

df["CO2_score"]   = 1 - df["n_CO2"]
df["Energy_score"] = 1 - df["n_Energy"]
df["Waste_score"] = 1 - df["n_Waste"]
df["Water_score"] = 1 - df["n_Water"]

df["Final_Score"] = 100 * (
    weights["CO2 emissions (Tons)"] * df["CO2_score"] +
    weights["Energy"]  * df["Energy_score"] +
    weights["Waste"]   * df["Waste_score"] +
    weights["Water"]   * df["Water_score"]
)

# Temporary cell to inspect raw 'Energy' column
temp_df = pd.read_csv("HiMCM 2025 - Processed Data (2).csv")
print("Raw 'Energy' column sample (first 10 unique non-numeric values):")
non_numeric_energy = temp_df['Energy'][pd.to_numeric(temp_df['Energy'], errors='coerce').isna()]
print(non_numeric_energy.head(10).unique())

df[["CO2", "Energy", "Waste", "Water", "Final_Score"]]

display(comparison_df)

superbowl_col = [col for col in df.columns if 'Superbowl' in col][0]
df.sort_values(by='Final_Score', ascending=False)[[superbowl_col, "CO2", "Energy", "Waste", "Water", "Final_Score"]]

from matplotlib import pyplot as plt
top_10_stadiums['Water'].plot(kind='line', figsize=(8, 4), title='Water')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10['Waste'].plot(kind='line', figsize=(8, 4), title='Waste')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_9['Energy'].plot(kind='line', figsize=(8, 4), title='Energy')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_8['CO2'].plot(kind='line', figsize=(8, 4), title='CO2')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='Water', y='Final_Score', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='Waste', y='Water', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='Energy', y='Waste', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='CO2', y='Energy', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['Water'].plot(kind='hist', bins=20, title='Water')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['Waste'].plot(kind='hist', bins=20, title='Waste')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Energy'].plot(kind='hist', bins=20, title='Energy')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_0['CO2'].plot(kind='hist', bins=20, title='CO2')
plt.gca().spines[['top', 'right',]].set_visible(False)



stadium_names = ["M&T Bank Stadium", "Huntington Bank Field", "Soldier Field"]
stadium_scores = df[df[superbowl_col].str.contains('|'.join(stadium_names), case=False)][[superbowl_col, "Final_Score"]]
display(stadium_scores)



"""**Reasoning**:
Load the raw CSV file into a temporary DataFrame and inspect the 'CO2' column for unique non-numeric values and the presence of numeric '0'.


"""

temp_raw_df = pd.read_csv(csv_file + ".csv")

print("Raw 'CO2' column sample (first 10 unique non-numeric values):")
non_numeric_co2 = temp_raw_df['CO2'][pd.to_numeric(temp_raw_df['CO2'], errors='coerce').isna()]
print(non_numeric_co2.head(10).unique())

# Check for numeric '0' after coercing non-numeric values
co2_numeric_check = pd.to_numeric(temp_raw_df['CO2'], errors='coerce')
if 0 in co2_numeric_check.unique():
    print(f"\nThe numeric value '0' exists in the 'CO2' column.")
else:
    print(f"\nThe numeric value '0' does not exist in the 'CO2' column.")

"""The inspection of the raw 'CO2' column confirmed two key points:

*   **Non-numeric values:** There are values that appear as numbers but are represented as strings containing commas (e.g., '2,550,000'). These need to be cleaned by removing commas and converting to a numeric type.
*   **Numeric '0' values:** The numeric value '0' explicitly exists in the 'CO2' column. As per the task's directive, these '0' values are considered 'uninputted' and should be converted to `NaN` before imputation.

Based on these findings, the next steps will involve:

1.  Modifying the data cleaning process for the 'CO2' column to convert '0's to `NaN`.
2.  Re-running the data cleaning, mean imputation, normalization, and scoring calculations.
3.  Displaying the updated top 10 stadiums to observe the impact of these changes.

**Reasoning**:
Based on the findings from the 'CO2' column inspection, I will now re-execute the data cleaning, mean imputation, normalization, and scoring steps. The crucial modification will be to treat numeric '0' values in the 'CO2' column as 'uninputted' data, converting them to `NaN` before imputation, and then re-calculating the scores and displaying the updated top 10 stadiums.
"""

df = pd.read_csv("HiMCM 2025 - Processed Data (2).csv")

# Clean 'CO2' column
df["CO2"] = df["CO2"].astype(str).str.replace("net 0", "", regex=False) # Treat 'net 0' as missing
df["CO2"] = df["CO2"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["CO2"] = pd.to_numeric(df["CO2"], errors='coerce') # Convert to numeric, coercing errors
df["CO2"] = df["CO2"].replace(0, np.nan) # Convert numeric 0 to NaN

# Clean 'Energy' column
df["Energy"] = df["Energy"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["Energy"] = pd.to_numeric(df["Energy"], errors='coerce') # Ensure numeric

# Clean 'Waste' column
df["Waste"] = df["Waste"].astype(str).str.replace("%", "", regex=False) # Remove percentage sign
df["Waste"] = pd.to_numeric(df["Waste"], errors='coerce') # Convert to numeric

# Clean 'Water' column
df["Water"] = pd.to_numeric(df["Water"], errors='coerce') # Ensure numeric

# Fill NaN values with the mean of their respective columns
for col in ["CO2", "Energy", "Waste", "Water"]:
    if df[col].isnull().any(): # Check if there are any NaN values in the column
        mean_value = df[col].mean()
        df[col] = df[col].fillna(mean_value)


required_cols = ["CO2", "Energy", "Waste", "Water"]
assert all(col in df.columns for col in required_cols), \
    f"CSV must contain: {required_cols}"

# Re-normalize columns
df["n_CO2"] = normalize(df["CO2"])
df["n_Energy"] = normalize(df["Energy"])
df["n_Waste"] = normalize(df["Waste"])
df["n_Water"] = normalize(df["Water"])

# Re-calculate scores
df["CO2_score"]   = 1 - df["n_CO2"]
df["Energy_score"] = 1 - df["n_Energy"]
df["Waste_score"] = 1 - df["n_Waste"]
df["Water_score"] = 1 - df["n_Water"]

df["Final_Score"] = 100 * (
    weights["CO2 emissions (Tons)"] * df["CO2_score"] +
    weights["Energy"]  * df["Energy_score"] +
    weights["Waste"]   * df["Waste_score"] +
    weights["Water"]   * df["Water_score"]
)

# Display the updated top 10 stadiums
superbowl_col = [col for col in df.columns if 'Superbowl' in col][0]
df.sort_values(by='Final_Score', ascending=False)[[superbowl_col, "CO2", "Energy", "Waste", "Water", "Final_Score"]].head(10)

"""## Final Task

### Subtask:
Summarize the changes made to the CO2 figures and how they impacted the environmental scores, along with displaying the updated top 10 stadiums.

## Summary:

### Q&A
The task to address potentially 'uninputted' CO2 values by inspecting raw data, converting problematic values (including `0`) to `NaN`, and then re-running data cleaning, imputation, normalization, and scoring calculations, followed by displaying the updated top 10 stadiums, was successfully completed.

### Data Analysis Key Findings
*   Initial inspection of the raw `CO2` column revealed non-numeric string values containing commas (e.g., '2,550,000') and explicit numeric `0` values.
*   The numeric `0` values in the `CO2` column were identified as 'uninputted' and were converted to `NaN` during the cleaning process.
*   The data cleaning, mean imputation, normalization, and scoring calculations were re-executed after these modifications to the `CO2` data.
*   The `Final_Score` and the ranking of the top 10 stadiums were updated as a result of these changes in `CO2` value handling.

### Insights or Next Steps
*   The re-evaluation of `CO2` data, particularly treating `0` as `NaN`, significantly influenced the environmental scores and the subsequent ranking of stadiums.
*   A comparative analysis between the previous and current top 10 stadium rankings, highlighting specific changes in `Final_Score` and position for affected stadiums, would provide deeper insights into the impact of the data cleaning modification.

# Task
Load the raw `CO2` data from "HiMCM 2025 - Processed Data (2).csv" into a temporary DataFrame. Then, display the raw `CO2` column from this temporary DataFrame side-by-side with the cleaned `CO2` column from the processed `df` DataFrame. After the display, provide a summary of the observed differences and the impact of the cleaning on the `CO2` values.

## Load Raw CO2 Data

### Subtask:
Load the raw CSV file into a temporary DataFrame and extract the original 'CO2' column before any cleaning or imputation.

**Reasoning**:
To compare the original and cleaned 'CO2' columns, I need to load the raw CSV file and extract the 'CO2' column from it, and also get the 'CO2' column from the already processed DataFrame.
"""

raw_df = pd.read_csv(csv_file + ".csv")
original_co2 = raw_df['CO2']
cleaned_co2 = df['CO2']

print("Original 'CO2' column from raw data:")
print(original_co2.head())
print("\nCleaned 'CO2' column from processed data:")
print(cleaned_co2.head())

"""**Reasoning**:
To effectively compare the original and cleaned 'CO2' columns and visualize the changes, I need to combine them into a single DataFrame and display it.

## Summary:

### Data Analysis Key Findings

*   The raw 'CO2' column, initially of 'object' data type, contained string values with commas (e.g., '2,550,000') and literal '0's, while the cleaned 'CO2' column was converted to a 'float64' data type.
*   The cleaning process transformed string values like '2,550,000' into numeric floats and handled 'net 0' entries by converting them to missing values.
*   A significant change was the handling of '0' values in the original data; these were converted to `NaN` (missing values) and subsequently imputed with the mean of the 'CO2' column, which is approximately 1,309,926. For example, original '0' values in rows 1 and 7 were replaced by `1.309926e+06` in the cleaned column.
*   This imputation of '0' values directly impacts the `CO2_score` (calculated as 1 - normalized\_CO2) and, consequently, the `Final_Score`, which incorporates `CO2_score` with a 0.4 weight.

### Insights or Next Steps

*   The decision to impute original '0' CO2 values with the mean suggests an assumption that true zero emissions are unlikely and that these values likely represent missing or unrecorded data, thereby providing a more realistic baseline for emissions analysis.
*   Further analysis could involve exploring the distribution of the imputed 'CO2' values compared to the original non-zero values to ensure the imputation strategy does not introduce undue bias, especially given the significant change from zero to a large mean value.

# Task
The task has been completed.
I've provided a summary of the observed differences and the impact of the cleaning on the `CO2` values, including a comparison of the raw and cleaned `CO2` columns.

Is there anything else I can help you with?

## Load Raw CO2 Data

### Subtask:
Load the raw CSV file into a temporary DataFrame and extract the original 'CO2' column before any cleaning or imputation.

**Reasoning**:
To compare the original and cleaned 'CO2' columns, I need to load the raw CSV file into a temporary DataFrame and extract the 'CO2' column from it, and also get the 'CO2' column from the already processed DataFrame.
"""

raw_df = pd.read_csv(csv_file + ".csv")
original_co2 = raw_df['CO2']
cleaned_co2 = df['CO2']

print("Original 'CO2' column from raw data:")
print(original_co2.head())
print("\nCleaned 'CO2' column from processed data:")
print(cleaned_co2.head())

"""**Reasoning**:
To effectively compare the original and cleaned 'CO2' columns and visualize the changes, I need to combine them into a single DataFrame and display it.


"""

comparison_df = pd.DataFrame({
    'Original CO2': original_co2,
    'Cleaned CO2': cleaned_co2
})

print("Side-by-side comparison of Original and Cleaned 'CO2' columns:")
display(comparison_df.head(10))

"""## Create CO2 Histogram

### Subtask:
Generate a histogram for the 'CO2' column to visualize its distribution and frequency.

**Reasoning**:
I will generate a histogram for the 'CO2' column using `matplotlib.pyplot` to visualize its distribution, setting the title and removing unnecessary plot spines for better aesthetics.
"""

from matplotlib import pyplot as plt
import matplotlib.ticker as mticker

ax = df['CO2'].plot(kind='hist', bins=20, title='CO2 Distribution', figsize=(10, 6))
plt.gca().spines[['top', 'right']].set_visible(False)

# Set x-axis formatter to display full numbers without scientific notation
formatter = mticker.ScalarFormatter(useOffset=False, useMathText=False)
formatter.set_scientific(False)
ax.xaxis.set_major_formatter(formatter)

plt.xlabel('CO2 Emissions (Tons)')
plt.ylabel('Frequency')
plt.tight_layout() # Adjust layout to prevent labels from being cut off

"""## Create Energy Histogram

### Subtask:
Generate a histogram for the 'Energy' column to visualize its distribution and frequency.

**Reasoning**:
I will generate a histogram for the 'Energy' column using `matplotlib.pyplot` to visualize its distribution, setting the title and removing unnecessary plot spines for better aesthetics.
"""

from matplotlib import pyplot as plt

df['Energy'].plot(kind='hist', bins=20, title='Energy Distribution')
plt.gca().spines[['top', 'right']].set_visible(False)

"""## Create Waste Histogram

### Subtask:
Generate a histogram for the 'Waste' column to visualize its distribution and frequency.

**Reasoning**:
I will generate a histogram for the 'Waste' column to visualize its distribution and frequency, setting the title and removing unnecessary plot spines for better aesthetics.
"""

from matplotlib import pyplot as plt

df['Waste'].plot(kind='hist', bins=20, title='Waste Distribution')
plt.gca().spines[['top', 'right']].set_visible(False)

"""## Create Water Histogram

### Subtask:
Generate a histogram for the 'Water' column to visualize its distribution and frequency.

## Create Water Histogram

### Subtask:
Generate a histogram for the 'Water' column to visualize its distribution and frequency.

**Reasoning**:
I will generate a histogram for the 'Water' column using `matplotlib.pyplot` to visualize its distribution, setting the title and removing unnecessary plot spines for better aesthetics, as per the instructions.
"""

from matplotlib import pyplot as plt

df['Water'].plot(kind='hist', bins=20, title='Water Distribution')
plt.gca().spines[['top', 'right']].set_visible(False)

"""**WORLD CUP ANALYSIS**"""

import pandas as pd
import numpy as np

# CSV filename
csv_file = "HiMCM 2025 - World Cup Processed Data"  # <-- CHANGE THIS

# weights MUST sum to 1
weights = {
    "CO2 emissions (Tons)": 0.4,
    "Energy": 0.3,
    "Waste": 0.2,
    "Water": 0.1
}

df = pd.read_csv("HiMCM 2025 - World Cup Processed Data.csv")
df.columns = df.columns.str.strip()

# Clean 'CO2' column
df["CO2"] = df["CO2"].astype(str).str.replace("net 0", "0", regex=False) # Replace 'net 0' with '0'
df["CO2"] = df["CO2"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["CO2"] = pd.to_numeric(df["CO2"], errors='coerce') # Convert to numeric, coercing errors

# Clean 'Energy' column
df["Energy"] = df["Energy"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["Energy"] = pd.to_numeric(df["Energy"], errors='coerce') # Ensure numeric

# Clean 'Waste' column
df["Waste"] = df["Waste"].astype(str).str.replace("%", "", regex=False) # Remove percentage sign
df["Waste"] = pd.to_numeric(df["Waste"], errors='coerce') # Convert to numeric

# Clean 'Water' column
df["Water"] = pd.to_numeric(df["Water"], errors='coerce') # Ensure numeric

# Fill NaN values with the mean of their respective columns
for col in ["CO2", "Energy", "Waste", "Water"]:
    if df[col].isnull().any(): # Check if there are any NaN values in the column
        mean_value = df[col].mean()
        df[col] = df[col].fillna(mean_value)


required_cols = ["CO2", "Energy", "Waste", "Water"]
assert all(col in df.columns for col in required_cols), \
    f"CSV must contain: {required_cols}"

df.head()

"""# Task
Strip whitespace from all column names in the `df` DataFrame immediately after reading the `HiMCM 2025 - World Cup Processed Data.csv` file, then re-execute the entire data cleaning, imputation, normalization, and scoring process, and display the first 5 rows of the resulting DataFrame.

## Strip Whitespace from Column Names

### Subtask:
Add a line to strip whitespace from all column names immediately after reading the CSV file to ensure consistent and correct column access.

**Reasoning**:
To address the 'KeyError: 'Water'', I will reload the CSV, immediately strip whitespace from all column names, and then re-execute the subsequent data cleaning, imputation, normalization, and scoring steps as instructed to ensure consistent column access.
"""

df = pd.read_csv("HiMCM 2025 - World Cup Processed Data.csv")
df.columns = df.columns.str.strip()

# Clean 'CO2' column
df["CO2"] = df["CO2"].astype(str).str.replace("net 0", "0", regex=False) # Replace 'net 0' with '0'
df["CO2"] = df["CO2"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["CO2"] = pd.to_numeric(df["CO2"], errors='coerce') # Convert to numeric, coercing errors

# Clean 'Energy' column
df["Energy"] = df["Energy"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["Energy"] = pd.to_numeric(df["Energy"], errors='coerce') # Ensure numeric

# Clean 'Waste' column
df["Waste"] = df["Waste"].astype(str).str.replace("%", "", regex=False) # Remove percentage sign
df["Waste"] = pd.to_numeric(df["Waste"], errors='coerce') # Convert to numeric

# Clean 'Water' column
df["Water"] = pd.to_numeric(df["Water"], errors='coerce') # Ensure numeric

# Fill NaN values with the mean of their respective columns
for col in ["CO2", "Energy", "Waste", "Water"]:
    if df[col].isnull().any(): # Check if there are any NaN values in the column
        mean_value = df[col].mean()
        df[col] = df[col].fillna(mean_value)


required_cols = ["CO2", "Energy", "Waste", "Water"]
assert all(col in df.columns for col in required_cols), \
    f"CSV must contain: {required_cols}"

df.head()

"""**Reasoning**:
The previous code block reloaded the data and cleaned some columns, but it missed the normalization and scoring steps, as well as the final display of the first 5 rows after all steps are complete. I will re-execute the entire cleaning, normalization, and scoring process as specified in the subtask.


"""

df = pd.read_csv("HiMCM 2025 - World Cup Processed Data.csv")
df.columns = df.columns.str.strip()

# Clean 'CO2' column
df["CO2"] = df["CO2"].astype(str).str.replace("net 0", "0", regex=False) # Replace 'net 0' with '0'
df["CO2"] = df["CO2"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["CO2"] = pd.to_numeric(df["CO2"], errors='coerce') # Convert to numeric, coercing errors

# Clean 'Energy' column
df["Energy"] = df["Energy"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["Energy"] = pd.to_numeric(df["Energy"], errors='coerce') # Ensure numeric

# Clean 'Waste' column
df["Waste"] = df["Waste"].astype(str).str.replace("%", "", regex=False) # Remove percentage sign
df["Waste"] = pd.to_numeric(df["Waste"], errors='coerce') # Convert to numeric

# Clean 'Water' column
df["Water"] = pd.to_numeric(df["Water"], errors='coerce') # Ensure numeric

# Fill NaN values with the mean of their respective columns
for col in ["CO2", "Energy", "Waste", "Water"]:
    if df[col].isnull().any(): # Check if there are any NaN values in the column
        mean_value = df[col].mean()
        df[col] = df[col].fillna(mean_value)


required_cols = ["CO2", "Energy", "Waste", "Water"]
assert all(col in df.columns for col in required_cols), \
    f"CSV must contain: {required_cols}"


def normalize(series):
    return np.clip((series - series.min()) / (series.max() - series.min()), 0, 1)

# Normalize columns
df["n_CO2"] = normalize(df["CO2"])
df["n_Energy"] = normalize(df["Energy"])
df["n_Waste"] = normalize(df["Waste"])
df["n_Water"] = normalize(df["Water"])

# Calculate scores (assuming higher is better for environmental impact)
df["CO2_score"]   = 1 - df["n_CO2"]
df["Energy_score"] = 1 - df["n_Energy"]
df["Waste_score"] = 1 - df["n_Waste"]
df["Water_score"] = 1 - df["n_Water"]

# Calculate Final Score
df["Final_Score"] = 100 * (
    weights["CO2 emissions (Tons)"] * df["CO2_score"] +
    weights["Energy"]  * df["Energy_score"] +
    weights["Waste"]   * df["Waste_score"] +
    weights["Water"]   * df["Water_score"]
)

df.head()

"""**Reasoning**:
The previous execution resulted in `NaN` values in the `Water` column, and consequently in `Final_Score`, because the `Water` column in the World Cup data was entirely `NaN` after numeric conversion, causing its mean to be `NaN` and the `fillna` operation to be ineffective. Furthermore, the existing `normalize` function would produce `NaN` if a series contained only identical values (e.g., all zeros after imputation). To ensure a successful calculation of `Final_Score` and adhere to the task of re-executing the cleaning and scoring steps, I will make two key adjustments:
1.  In the imputation loop, if a column's mean is `NaN` (indicating all values are missing for that column), I will fill `NaN` values with `0` as a pragmatic default to allow calculations to proceed. This assumes that 'no data' for an environmental metric can be interpreted as 'no impact' (best possible scenario, which when normalized to 0, results in a score of 1).
2.  I will redefine the `normalize` function to correctly handle cases where all values in a series are identical. If all values are 0, they will normalize to 0; otherwise (for a constant non-zero series), they will normalize to 0.5 (a neutral position). This prevents division-by-zero errors and `NaN` propagation during normalization.


"""

import pandas as pd
import numpy as np

# Assuming weights and csv_file are defined in previous cells and are available in the kernel
# weights MUST sum to 1
weights = {
    "CO2 emissions (Tons)": 0.4,
    "Energy": 0.3,
    "Waste": 0.2,
    "Water": 0.1
}
csv_file = "HiMCM 2025 - World Cup Processed Data"

df = pd.read_csv(csv_file + ".csv")
df.columns = df.columns.str.strip()

# Clean 'CO2' column
df["CO2"] = df["CO2"].astype(str).str.replace("net 0", "0", regex=False) # Replace 'net 0' with '0'
df["CO2"] = df["CO2"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["CO2"] = pd.to_numeric(df["CO2"], errors='coerce') # Convert to numeric, coercing errors

# Clean 'Energy' column
df["Energy"] = df["Energy"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["Energy"] = pd.to_numeric(df["Energy"], errors='coerce') # Ensure numeric

# Clean 'Waste' column
df["Waste"] = df["Waste"].astype(str).str.replace("%", "", regex=False) # Remove percentage sign
df["Waste"] = pd.to_numeric(df["Waste"], errors='coerce') # Convert to numeric

# Clean 'Water' column
df["Water"] = pd.to_numeric(df["Water"], errors='coerce') # Ensure numeric

# Fill NaN values with the mean of their respective columns
for col in ["CO2", "Energy", "Waste", "Water"]:
    if df[col].isnull().any(): # Check if there are any NaN values in the column
        mean_value = df[col].mean()
        # If mean_value is NaN (meaning the entire column is NaN after numeric conversion),
        # fill with 0 to prevent NaN propagation, as no valid mean can be calculated.
        if pd.isna(mean_value):
            df[col] = df[col].fillna(0)
        else:
            df[col] = df[col].fillna(mean_value)


required_cols = ["CO2", "Energy", "Waste", "Water"]
assert all(col in df.columns for col in required_cols), \
    f"CSV must contain: {required_cols}"

def normalize(series):
    min_val = series.min()
    max_val = series.max()
    if pd.isna(min_val) or pd.isna(max_val): # If series is all NaNs, min/max will be NaN
        return series * np.nan # Propagate NaNs for a fully NaN series (should be handled by fillna above)
    if max_val == min_val: # All values are the same
        if min_val == 0: # If all values are 0, normalize to 0 (best possible)
            return series.apply(lambda x: 0)
        else: # If all values are a constant non-zero, normalize to 0.5 (neutral)
            return series.apply(lambda x: 0.5)
    return np.clip((series - min_val) / (max_val - min_val), 0, 1)

# Normalize columns
df["n_CO2"] = normalize(df["CO2"])
df["n_Energy"] = normalize(df["Energy"])
df["n_Waste"] = normalize(df["Waste"])
df["n_Water"] = normalize(df["Water"])

# Calculate scores (assuming higher is better for environmental impact)
df["CO2_score"]   = 1 - df["n_CO2"]
df["Energy_score"] = 1 - df["n_Energy"]
df["Waste_score"] = 1 - df["n_Waste"]
df["Water_score"] = 1 - df["n_Water"]

# Calculate Final Score
df["Final_Score"] = 100 * (
    weights["CO2 emissions (Tons)"] * df["CO2_score"] +
    weights["Energy"]  * df["Energy_score"] +
    weights["Waste"]   * df["Waste_score"] +
    weights["Water"]   * df["Water_score"]
)

df.head()

"""## Summary:

### Data Analysis Key Findings
*   **Whitespace Stripping:** Whitespace was successfully stripped from all column names immediately after reading the CSV file, which addressed potential `KeyError` issues and ensured correct column access.
*   **Initial Data Cleaning & Imputation Issues:** After initial cleaning, the 'Water' column contained `NaN` values, and in some cases, the entire column became `NaN` after converting to numeric types. This propagated `NaN`s through the normalization and scoring steps, resulting in `NaN` values in the `Final_Score`.
*   **Improved Imputation Logic:** The imputation process was enhanced to handle cases where a column became entirely `NaN` after numeric conversion (meaning its mean would also be `NaN`). In such scenarios, `NaN`s were filled with `0` to prevent `NaN` propagation. Otherwise, they were filled with the column's mean.
*   **Robust Normalization:** The `normalize` function was made more robust to prevent `NaN`s arising from columns where all values were identical (e.g., all zeros or all constant non-zeros). Specifically, a series of all zeros normalizes to `0`, and a series of constant non-zeros normalizes to `0.5`, avoiding division by zero.
*   **Successful Score Calculation:** With the improved imputation and normalization logic, the entire data processing pipeline (cleaning, imputation, normalization, and scoring) was successfully re-executed, yielding a DataFrame with valid numeric `Final_Score` values for all entries.

### Insights or Next Steps
*   The robustness added to the data cleaning pipeline, particularly for handling completely missing or constant-valued columns, is crucial for maintaining data integrity and ensuring consistent analytical outputs. This approach should be consistently applied in future data processing tasks.
*   Consider implementing data quality checks earlier in the pipeline to identify and flag columns that are entirely `NaN` or constant *before* advanced processing, allowing for more specific remediation strategies if the `0` or `0.5` imputation is not semantically appropriate for certain data types.

# Task
**Reasoning**:
I need to inspect the raw 'Water' column from the 'HiMCM 2025 - World Cup Processed Data.csv' file to understand why it resulted in `NaN` values after numeric conversion. This will involve loading the CSV into a temporary DataFrame and identifying any unique non-numeric entries in the 'Water' column that prevent it from being correctly converted to a numeric data type.

## Inspect Raw 'Water' Column

### Subtask:
Load the 'HiMCM 2025 - World Cup Processed Data.csv' into a temporary DataFrame and identify any unique non-numeric values in the 'Water' column that are preventing it from being converted to numeric type. This will help understand why it's becoming NaN.

**Reasoning**:
To identify unique non-numeric values in the 'Water' column that cause `NaN` after numeric conversion, I will load the raw CSV, use `pd.to_numeric` to find problematic entries, and then display the first 10 unique non-numeric values.
"""

temp_raw_df = pd.read_csv("HiMCM 2025 - World Cup Processed Data.csv")

print("Raw 'Water' column sample (first 10 unique non-numeric values):")
non_numeric_water = temp_raw_df['Water'][pd.to_numeric(temp_raw_df['Water'], errors='coerce').isna()]
print(non_numeric_water.head(10).unique())

"""**Reasoning**:
The previous code failed with a `KeyError: 'Water'`, indicating the column name 'Water' was not found in `temp_raw_df`. This is likely due to leading or trailing whitespace in the column names of the raw CSV. To fix this, I will strip whitespace from the column names of `temp_raw_df` immediately after loading the CSV, similar to how it was done for the main `df`.


"""

temp_raw_df = pd.read_csv("HiMCM 2025 - World Cup Processed Data.csv")
temp_raw_df.columns = temp_raw_df.columns.str.strip()

print("Raw 'Water' column sample (first 10 unique non-numeric values):")
non_numeric_water = temp_raw_df['Water'][pd.to_numeric(temp_raw_df['Water'], errors='coerce').isna()]
print(non_numeric_water.head(10).unique())

"""## Summary:

### Data Analysis Key Findings
*   The inspection of the raw 'Water' column after stripping whitespace from column names revealed that the column contained string values with commas (e.g., '612,900', '1,000,000').
*   These string values prevent direct conversion to a numeric type, leading to `NaN` values if `errors='coerce'` is used without prior cleaning.
*   This explains why the 'Water' column was found to be entirely `NaN` after the initial numeric conversion attempts in previous steps, causing issues with normalization and `Final_Score` calculation.

### Insights or Next Steps
*   The immediate next step in the data cleaning process for the 'World Cup Processed Data' should involve removing commas from the 'Water' column values and then converting them to a numeric type. This will ensure that the `Water` column can be properly imputed, normalized, and used in the `Final_Score` calculation.

## Summary:

### Data Analysis Key Findings
*   The inspection of the raw 'Water' column after stripping whitespace from column names revealed that the column contained string values with commas (e.g., '612,900', '1,000,000').
*   These string values prevent direct conversion to a numeric type, leading to `NaN` values if `errors='coerce'` is used without prior cleaning.
*   This explains why the 'Water' column was found to be entirely `NaN` after the initial numeric conversion attempts in previous steps, causing issues with normalization and `Final_Score` calculation.

### Insights or Next Steps
*   The immediate next step in the data cleaning process for the 'World Cup Processed Data' should involve removing commas from the 'Water' column values and then converting them to a numeric type. This will ensure that the `Water` column can be properly imputed, normalized, and used in the `Final_Score` calculation.

## Clean 'Water' Column and Re-process Data

### Subtask:
Based on the findings from the inspection, apply specific cleaning steps to the 'Water' column (e.g., removing commas, spaces, or other non-numeric characters) to enable correct numeric conversion. Then, re-execute the entire data cleaning, mean imputation, normalization, and scoring process for the World Cup data with this improved 'Water' column handling.

**Reasoning**:
Based on the identified non-numeric values in the 'Water' column, I will now re-execute the entire data cleaning, mean imputation, normalization, and scoring process, including the specific instruction to remove commas from the 'Water' column and replace numeric '0' values in 'CO2' with NaN for proper handling before imputation.
"""

import pandas as pd
import numpy as np

# Reload the CSV file and strip whitespace from column names
df = pd.read_csv("HiMCM 2025 - World Cup Processed Data.csv")
df.columns = df.columns.str.strip()

# Clean 'CO2' column
df["CO2"] = df["CO2"].astype(str).str.replace("net 0", "0", regex=False) # Replace 'net 0' with '0'
df["CO2"] = df["CO2"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["CO2"] = pd.to_numeric(df["CO2"], errors='coerce') # Convert to numeric, coercing errors
df["CO2"] = df["CO2"].replace(0, np.nan) # Convert numeric 0 to NaN

# Clean 'Energy' column
df["Energy"] = df["Energy"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["Energy"] = pd.to_numeric(df["Energy"], errors='coerce') # Ensure numeric

# Clean 'Waste' column
df["Waste"] = df["Waste"].astype(str).str.replace("%", "", regex=False) # Remove percentage sign
df["Waste"] = pd.to_numeric(df["Waste"], errors='coerce') # Convert to numeric

# Clean 'Water' column: remove commas and convert to numeric
df["Water"] = df["Water"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["Water"] = pd.to_numeric(df["Water"], errors='coerce') # Ensure numeric

# Fill NaN values with the mean of their respective columns, or 0 if mean is NaN
for col in ["CO2", "Energy", "Waste", "Water"]:
    if df[col].isnull().any(): # Check if there are any NaN values in the column
        mean_value = df[col].mean()
        # If mean_value is NaN (meaning the entire column is NaN after numeric conversion),
        # fill with 0 to prevent NaN propagation, as no valid mean can be calculated.
        if pd.isna(mean_value):
            df[col] = df[col].fillna(0)
        else:
            df[col] = df[col].fillna(mean_value)

# Assert that required columns exist
required_cols = ["CO2", "Energy", "Waste", "Water"]
assert all(col in df.columns for col in required_cols), \
    f"CSV must contain: {required_cols}"

# Define normalization function
def normalize(series):
    min_val = series.min()
    max_val = series.max()
    if pd.isna(min_val) or pd.isna(max_val): # If series is all NaNs, min/max will be NaN
        return series * np.nan # Propagate NaNs for a fully NaN series
    if max_val == min_val: # All values are the same
        if min_val == 0: # If all values are 0, normalize to 0 (best possible)
            return series.apply(lambda x: 0)
        else: # If all values are a constant non-zero, normalize to 0.5 (neutral)
            return series.apply(lambda x: 0.5)
    return np.clip((series - min_val) / (max_val - min_val), 0, 1)

# Normalize columns
df["n_CO2"] = normalize(df["CO2"])
df["n_Energy"] = normalize(df["Energy"])
df["n_Waste"] = normalize(df["Waste"])
df["n_Water"] = normalize(df["Water"])

# Calculate scores (assuming higher is better for environmental impact)
df["CO2_score"]   = 1 - df["n_CO2"]
df["Energy_score"] = 1 - df["n_Energy"]
df["Waste_score"] = 1 - df["n_Waste"]
df["Water_score"] = 1 - df["n_Water"]

# Calculate Final Score using pre-defined weights
# weights MUST sum to 1
weights = {
    "CO2 emissions (Tons)": 0.4,
    "Energy": 0.3,
    "Waste": 0.2,
    "Water": 0.1
}

df["Final_Score"] = 100 * (
    weights["CO2 emissions (Tons)"] * df["CO2_score"] +
    weights["Energy"]  * df["Energy_score"] +
    weights["Waste"]   * df["Waste_score"] +
    weights["Water"]   * df["Water_score"]
)

# Display the first 5 rows of the DataFrame
df.head()

from matplotlib import pyplot as plt
import seaborn as sns
_df_16.groupby('Location for Football Tourney').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_14['Waste'].plot(kind='hist', bins=20, title='Waste')
plt.gca().spines[['top', 'right',]].set_visible(False)

"""## Display Processed Data Head

### Subtask:
Display the first few rows of the fully processed DataFrame, including the cleaned 'Water' column and the calculated 'Final_Score', to confirm the data is now correctly handled.

**Reasoning**:
To display the first 5 rows of the fully processed DataFrame, I will use `df.head()` to confirm the cleaned 'Water' column and the calculated 'Final_Score' are present and correctly populated.
"""

df.head()

"""## Display 'Water' and 'Final_Score' Columns

### Subtask:
Display the 'Location for Football Tourney', 'Water', and 'Final_Score' columns for all entries in the DataFrame to show the complete results and the impact of the improved cleaning.

**Reasoning**:
To fulfill the subtask, I will select the requested columns ('Location for Football Tourney', 'Water', and 'Final_Score') from the DataFrame `df` and display all rows.
"""

df[["Location for Football Tourney", "Water", "Final_Score"]]

"""## Final Task

### Subtask:
Summarize the changes made to the 'Water' column, how they impacted the environmental scores, and confirm that the data is now correctly processed.

## Summary:

### Q&A
1.  **What changes were made to the 'Water' column?**
    The 'Water' column, initially identified to contain string values with commas (e.g., '612,900', '1,000,000') and leading to `NaN` values upon numeric conversion, underwent a cleaning process. Commas were removed from its values, and then it was converted to a numeric data type.
2.  **How did these changes impact the environmental scores?**
    The cleaning of the 'Water' column allowed it to be correctly converted to a numeric type, which enabled proper mean imputation for any missing values. This, in turn, allowed the 'Water' column to be successfully normalized, and subsequently, the `Water_score` and the overall `Final_Score` could be accurately calculated for all entries in the dataset. Previously, `NaN` values in 'Water' would have propagated and led to incorrect or missing scores.
3.  **Is the data now correctly processed?**
    Yes, the data is now correctly processed. The 'Water' column contains numeric values, `NaN` values in all relevant environmental columns (`CO2`, `Energy`, `Waste`, `Water`) have been handled through mean imputation, and all individual environmental scores and the `Final_Score` have been successfully calculated and are present in the DataFrame.

### Data Analysis Key Findings
*   Initially, the 'Water' column was found to contain string values with commas (e.g., '612,900', '1,000,000'), which caused it to become entirely `NaN` during previous attempts at numeric conversion.
*   A `KeyError` for the 'Water' column was encountered and resolved by stripping whitespace from all column names after loading the CSV, revealing a hidden character issue in the original column name.
*   The 'Water' column was successfully cleaned by removing commas (`str.replace(",", "", regex=False)`) and then converted to a numeric data type (`pd.to_numeric(..., errors='coerce')`).
*   Mean imputation was applied to the `CO2`, `Energy`, `Waste`, and `Water` columns to fill any remaining `NaN` values, ensuring a complete dataset for scoring.
*   All environmental impact columns (`CO2`, `Energy`, `Waste`, `Water`) were successfully normalized and then converted into individual environmental scores (e.g., `CO2_score`, `Water_score`).
*   A `Final_Score` was calculated for each entry using weighted averages of the individual environmental scores, confirming the successful end-to-end processing of the data.

### Insights or Next Steps
*   The robust data cleaning process, including addressing hidden characters in column names and handling specific data formats (like commas in numbers), is crucial for accurate data analysis and model input.
*   The current processing pipeline can be applied reliably to similar datasets, ensuring that environmental scores are consistently and accurately derived, enabling fair comparison and decision-making for football tournament locations.
"""
