# -*- coding: utf-8 -*-
"""HiMCM25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aWNn53ETUM7SM8Z0Vt3uIA4ozVu5Z_DU
"""

import pandas as pd
import numpy as np

# CSV filename
csv_file = "HiMCM 2025 - Processed Data (2)"  # <-- CHANGE THIS

# weights MUST sum to 1
weights = {
    "CO2 emissions (Tons)": 0.4,
    "Energy": 0.3,
    "Waste": 0.2,
    "Water": 0.1
}

df = pd.read_csv("HiMCM 2025 - Processed Data (2).csv")

# Clean 'CO2' column
df["CO2"] = df["CO2"].astype(str).str.replace("net 0", "0", regex=False) # Replace 'net 0' with '0'
df["CO2"] = df["CO2"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["CO2"] = pd.to_numeric(df["CO2"], errors='coerce') # Convert to numeric, coercing errors

# Clean 'Energy' column
df["Energy"] = df["Energy"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["Energy"] = pd.to_numeric(df["Energy"], errors='coerce') # Ensure numeric

# Clean 'Waste' column
df["Waste"] = df["Waste"].astype(str).str.replace("%", "", regex=False) # Remove percentage sign
df["Waste"] = pd.to_numeric(df["Waste"], errors='coerce') # Convert to numeric

# Clean 'Water' column
df["Water"] = pd.to_numeric(df["Water"], errors='coerce') # Ensure numeric

# Fill NaN values with the mean of their respective columns
for col in ["CO2", "Energy", "Waste", "Water"]:
    if df[col].isnull().any(): # Check if there are any NaN values in the column
        mean_value = df[col].mean()
        df[col] = df[col].fillna(mean_value)


required_cols = ["CO2", "Energy", "Waste", "Water"]
assert all(col in df.columns for col in required_cols), \
    f"CSV must contain: {required_cols}"

df.head()

def normalize(series):
    return np.clip((series - series.min()) / (series.max() - series.min()), 0, 1)

df["n_CO2"] = normalize(df["CO2"])
df["n_Energy"] = normalize(df["Energy"])
df["n_Waste"] = normalize(df["Waste"])
df["n_Water"] = normalize(df["Water"])

df["CO2_score"]   = 1 - df["n_CO2"]
df["Energy_score"] = 1 - df["n_Energy"]
df["Waste_score"] = 1 - df["n_Waste"]
df["Water_score"] = 1 - df["n_Water"]

df["Final_Score"] = 100 * (
    weights["CO2 emissions (Tons)"] * df["CO2_score"] +
    weights["Energy"]  * df["Energy_score"] +
    weights["Waste"]   * df["Waste_score"] +
    weights["Water"]   * df["Water_score"]
)

# Temporary cell to inspect raw 'Energy' column
temp_df = pd.read_csv("HiMCM 2025 - Processed Data (2).csv")
print("Raw 'Energy' column sample (first 10 unique non-numeric values):")
non_numeric_energy = temp_df['Energy'][pd.to_numeric(temp_df['Energy'], errors='coerce').isna()]
print(non_numeric_energy.head(10).unique())

df[["CO2", "Energy", "Waste", "Water", "Final_Score"]]

superbowl_col = [col for col in df.columns if 'Superbowl' in col][0]
df.sort_values(by='Final_Score', ascending=False)[[superbowl_col, "CO2", "Energy", "Waste", "Water", "Final_Score"]]