# -*- coding: utf-8 -*-
"""WORLDCUP data analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sjzqA66tJSvinI6Y3HHSGUvpu2u2Upcr
"""

import pandas as pd
import numpy as np

# CSV filename
csv_file = "HiMCM 2025 - World Cup Processed Data"  # <-- CHANGE THIS

# weights MUST sum to 1
weights = {
    "CO2 emissions (Tons)": 0.4,
    "Energy": 0.3,
    "Waste": 0.2,
    "Water": 0.1
}

import pandas as pd
import numpy as np

# Reload the CSV file and strip whitespace from column names
df = pd.read_csv("HiMCM 2025 - World Cup Processed Data.csv")
df.columns = df.columns.str.strip()

# Clean 'CO2' column
df["CO2"] = df["CO2"].astype(str).str.replace("net 0", "0", regex=False) # Replace 'net 0' with '0'
df["CO2"] = df["CO2"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["CO2"] = pd.to_numeric(df["CO2"], errors='coerce') # Convert to numeric, coercing errors
df["CO2"] = df["CO2"].replace(0, np.nan) # Convert numeric 0 to NaN

# Clean 'Energy' column
df["Energy"] = df["Energy"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["Energy"] = pd.to_numeric(df["Energy"], errors='coerce') # Ensure numeric

# Clean 'Waste' column
df["Waste"] = df["Waste"].astype(str).str.replace("%", "", regex=False) # Remove percentage sign
df["Waste"] = pd.to_numeric(df["Waste"], errors='coerce') # Convert to numeric

# Clean 'Water' column: remove commas and convert to numeric
df["Water"] = df["Water"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["Water"] = pd.to_numeric(df["Water"], errors='coerce') # Ensure numeric

# Fill NaN values with the mean of their respective columns, or 0 if mean is NaN
for col in ["CO2", "Energy", "Waste", "Water"]:
    if df[col].isnull().any(): # Check if there are any NaN values in the column
        mean_value = df[col].mean()
        # If mean_value is NaN (meaning the entire column is NaN after numeric conversion),
        # fill with 0 to prevent NaN propagation, as no valid mean can be calculated.
        if pd.isna(mean_value):
            df[col] = df[col].fillna(0)
        else:
            df[col] = df[col].fillna(mean_value)

# Assert that required columns exist
required_cols = ["CO2", "Energy", "Waste", "Water"]
assert all(col in df.columns for col in required_cols), \
    f"CSV must contain: {required_cols}"

# Define normalization function
def normalize(series):
    min_val = series.min()
    max_val = series.max()
    if pd.isna(min_val) or pd.isna(max_val): # If series is all NaNs, min/max will be NaN
        return series * np.nan # Propagate NaNs for a fully NaN series
    if max_val == min_val: # All values are the same
        if min_val == 0: # If all values are 0, normalize to 0 (best possible)
            return series.apply(lambda x: 0)
        else: # If all values are a constant non-zero, normalize to 0.5 (neutral)
            return series.apply(lambda x: 0.5)
    return np.clip((series - min_val) / (max_val - min_val), 0, 1)

# Normalize columns
df["n_CO2"] = normalize(df["CO2"])
df["n_Energy"] = normalize(df["Energy"])
df["n_Waste"] = normalize(df["Waste"])
df["n_Water"] = normalize(df["Water"])

# Calculate scores (assuming higher is better for environmental impact)
df["CO2_score"]   = 1 - df["n_CO2"]
df["Energy_score"] = 1 - df["n_Energy"]
df["Waste_score"] = 1 - df["n_Waste"]
df["Water_score"] = 1 - df["n_Water"]

# Calculate Final Score using pre-defined weights
# weights MUST sum to 1
weights = {
    "CO2 emissions (Tons)": 0.4,
    "Energy": 0.3,
    "Waste": 0.2,
    "Water": 0.1
}

df["Final_Score"] = 100 * (
    weights["CO2 emissions (Tons)"] * df["CO2_score"] +
    weights["Energy"]  * df["Energy_score"] +
    weights["Waste"]   * df["Waste_score"] +
    weights["Water"]   * df["Water_score"]
)

# Display the first 5 rows of the DataFrame
df.head()

temp_raw_worldcup_df = pd.read_csv("HiMCM 2025 - World Cup Processed Data.csv")
temp_raw_worldcup_df.columns = temp_raw_worldcup_df.columns.str.strip()

print("Raw 'CO2' column sample (first 10 unique non-numeric values and 'net 0' check):")

# Identify non-numeric values by first converting to string and then coercing to numeric
# This helps catch 'net 0' and other string representations of numbers
co2_as_string = temp_raw_worldcup_df['CO2'].astype(str)
non_numeric_co2_initial = co2_as_string[pd.to_numeric(co2_as_string, errors='coerce').isna()]

# Also explicitly check for 'net 0'
if 'net 0' in co2_as_string.unique():
    print("\n'net 0' string value explicitly found in CO2 column.")

# Print other unique non-numeric values
if not non_numeric_co2_initial.empty:
    print("Other unique non-numeric CO2 values (before full cleaning):")
    print(non_numeric_co2_initial.head(10).unique())
else:
    print("No other unique non-numeric CO2 values (before full cleaning) found.")


# Prepare CO2 column for numeric check by first cleaning 'net 0' and commas
cleaned_co2_for_check = temp_raw_worldcup_df['CO2'].astype(str).str.replace('net 0', '0', regex=False)
cleaned_co2_for_check = cleaned_co2_for_check.str.replace(',', '', regex=False)
co2_numeric_check_final = pd.to_numeric(cleaned_co2_for_check, errors='coerce')

print("\nChecking for numeric '0' after initial string cleaning and coercion:")
if 0 in co2_numeric_check_final.unique():
    print(f"The numeric value '0' exists in the 'CO2' column after cleaning 'net 0' and commas.")
else:
    print(f"The numeric value '0' does not exist in the 'CO2' column after cleaning 'net 0' and commas.")

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

# Histogram for CO2 Distribution
fig_co2, ax_co2 = plt.subplots(figsize=(10, 6))
df['CO2'].plot(kind='hist', bins=5, title='CO2 Distribution (Tons)', ax=ax_co2)
ax_co2.spines[['top', 'right']].set_visible(False)
formatter_co2 = mticker.ScalarFormatter(useOffset=False, useMathText=False)
formatter_co2.set_scientific(False)
ax_co2.xaxis.set_major_formatter(formatter_co2)
plt.xlabel('CO2 Emissions (Tons)')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

# Histogram for Energy Distribution
fig_energy, ax_energy = plt.subplots(figsize=(10, 6))
df['Energy'].plot(kind='hist', bins=5, title='Energy Distribution', ax=ax_energy)
ax_energy.spines[['top', 'right']].set_visible(False)
formatter_energy = mticker.ScalarFormatter(useOffset=False, useMathText=False)
formatter_energy.set_scientific(False)
ax_energy.xaxis.set_major_formatter(formatter_energy)
plt.xlabel('Energy Consumption')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Histogram for Waste Distribution
fig_waste, ax_waste = plt.subplots(figsize=(10, 6))
df['Waste'].plot(kind='hist', bins=5, title='Waste Distribution (%)', ax=ax_waste)
ax_waste.spines[['top', 'right']].set_visible(False)
plt.xlabel('Waste (Percentage)')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

# Histogram for Water Distribution
fig_water, ax_water = plt.subplots(figsize=(10, 6))
df['Water'].plot(kind='hist', bins=5, title='Water Distribution', ax=ax_water)
ax_water.spines[['top', 'right']].set_visible(False)
formatter_water = mticker.ScalarFormatter(useOffset=False, useMathText=False)
formatter_water.set_scientific(False)
ax_water.xaxis.set_major_formatter(formatter_water)
plt.xlabel('Water Consumption')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np

# Reload the CSV file and strip whitespace from column names
df = pd.read_csv("HiMCM 2025 - World Cup Processed Data.csv")
df.columns = df.columns.str.strip()

# Clean 'CO2' column
df["CO2"] = df["CO2"].astype(str).str.replace("net 0", "0", regex=False) # Replace 'net 0' with '0'
df["CO2"] = df["CO2"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["CO2"] = pd.to_numeric(df["CO2"], errors='coerce') # Convert to numeric, coercing errors
df["CO2"] = df["CO2"].replace(0, np.nan) # Convert numeric 0 to NaN

# Clean 'Energy' column
df["Energy"] = df["Energy"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["Energy"] = pd.to_numeric(df["Energy"], errors='coerce') # Ensure numeric

# Clean 'Waste' column
df["Waste"] = df["Waste"].astype(str).str.replace("%", "", regex=False) # Remove percentage sign
df["Waste"] = pd.to_numeric(df["Waste"], errors='coerce') # Convert to numeric

# Clean 'Water' column: remove commas and convert to numeric
df["Water"] = df["Water"].astype(str).str.replace(",", "", regex=False) # Remove commas
df["Water"] = pd.to_numeric(df["Water"], errors='coerce') # Ensure numeric

# Fill NaN values with the mean of their respective columns, or 0 if mean is NaN
for col in ["CO2", "Energy", "Waste", "Water"]:
    if df[col].isnull().any(): # Check if there are any NaN values in the column
        mean_value = df[col].mean()
        # If mean_value is NaN (meaning the entire column is NaN after numeric conversion),
        # fill with 0 to prevent NaN propagation, as no valid mean can be calculated.
        if pd.isna(mean_value):
            df[col] = df[col].fillna(0)
        else:
            df[col] = df[col].fillna(mean_value)

# Assert that required columns exist
required_cols = ["CO2", "Energy", "Waste", "Water"]
assert all(col in df.columns for col in required_cols), \
    f"CSV must contain: {required_cols}"

# Define normalization function (robust to constant series)
def normalize(series):
    min_val = series.min()
    max_val = series.max()
    if pd.isna(min_val) or pd.isna(max_val): # If series is all NaNs, min/max will be NaN
        return series * np.nan # Propagate NaNs for a fully NaN series
    if max_val == min_val: # All values are the same
        if min_val == 0: # If all values are 0, normalize to 0 (best possible)
            return series.apply(lambda x: 0)
        else: # If all values are a constant non-zero, normalize to 0.5 (neutral)
            return series.apply(lambda x: 0.5)
    return np.clip((series - min_val) / (max_val - min_val), 0, 1)

# Normalize columns
df["n_CO2"] = normalize(df["CO2"])
df["n_Energy"] = normalize(df["Energy"])
df["n_Waste"] = normalize(df["Waste"])
df["n_Water"] = normalize(df["Water"])

# Calculate scores (assuming higher is better for environmental impact)
df["CO2_score"]   = 1 - df["n_CO2"]
df["Energy_score"] = 1 - df["n_Energy"]
df["Waste_score"] = 1 - df["n_Waste"]
df["Water_score"] = 1 - df["n_Water"]

# Calculate Final Score using pre-defined weights
# weights MUST sum to 1
# Assuming weights are already defined in the kernel from previous cells, if not, define here:
weights = {
    "CO2 emissions (Tons)": 0.4,
    "Energy": 0.3,
    "Waste": 0.2,
    "Water": 0.1
}

df["Final_Score"] = 100 * (
    weights["CO2 emissions (Tons)"] * df["CO2_score"] +
    weights["Energy"]  * df["Energy_score"] +
    weights["Waste"]   * df["Waste_score"] +
    weights["Water"]   * df["Water_score"]
)

# Display the first 5 rows of the DataFrame
df.head()